version: '3.4'

services:
  db:
    image: postgres
    restart: always
    container_name: local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.develop.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  postgres_data: