version: '3.4'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_PASSWORD: password

  build_map_admin:
    build:
      context: ./
      dockerfile: Dockerfile
    image: build_map_admin
    ports:
      - "3000:3000"

    restart: always
    container_name: build_map_admin
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./file_store:/app/storage
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      SECRET_KEY_BASE:

      RAILS_LOG_TO_STDOUT: 'true'

