print_client_class: PrintClient::DataToDocument
svg_file:
  roads_layer_name: Roads # Название уровня с маршрутами в svg файле
  normalize_coordinate_limit: 3 # До скольки знаков обрезать дробную часть координат
data_to_document:
  base_url: <%= ENV['DATA_TO_DOCUMENT_BASE_URL'] %>
qr_code:
  user_site_base_url: <%= ENV['USER_SITE_BASE_URL'] %>